In [3]:
import numpy as np

Exercice 1 : les constructeurs

In [27]:
1#Constructeur un tableau numpy qui contient les éléments suivants : 1,5,7,8
T = np.array([1,5,7,8])
print(T)

[1 5 7 8]


In [28]:
2#Constructeur un tableau numpy qui contient les éléments suivants :1,2,3,4,5,6,7,8,9
T1 = np.array([1,2,3,4,5,6,7,8,9])
print(T1)

[1 2 3 4 5 6 7 8 9]


In [29]:
3#Créer un tableau de 10 éléments rempli de 0
T2 = np.zeros(10)
print(T2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
4#Créer un tableau de 2 lignes 5 colonnes rempli de 0
T3 = np.zeros((2, 5))
print(T3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [31]:
5#Créer un tableau de 10 éléments rempli de 1
T4 = np.ones(10)
print(T4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [32]:
6#Créer un tableau de 2 lignes 5 colonnes rempli de 1
T5 = np.ones((2, 5))
print(T5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
7#Créer un tableau de 10 éléments rempli 8.5
T6 = np.full(10, 8.5)
print(T6)

[8.5 8.5 8.5 8.5 8.5 8.5 8.5 8.5 8.5 8.5]


In [34]:
8#Créer un tableau de série d'entiers successifs allant de 1 à 9 inclus
T7= np.arange(1, 10)
print(T7)

[1 2 3 4 5 6 7 8 9]


In [35]:
9#Créer un tableau de 3 lignes et 3 colonnes rempli de série d'entiers successifs allant de 1 à 9 inclus
tableau= np.arange(1, 10)
T8=tableau.reshape(3, 3)
print(T8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
10#Créer une matrice identité de 4 lignes 4 colonnes
matrice_identite = np.eye(4)
print(matrice_identite)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [51]:
11#Tableau rempli de valeurs aléatoires normales centrées en zéro
tableau_valeur = np.random.normal(0, 1, (3, 3))
print(tableau_valeur)

[[ 0.59947049 -0.26864032 -0.06055051]
 [-0.29958067 -0.17105468  1.01144186]
 [ 1.38897112 -1.37188202 -0.27705574]]


In [118]:
12#Créer un tableau rempli de 20 valeurs aléatoires entières comprises entre 1 et 10
tableau_entiers_aleatoires = np.random.randint(1, 11, 20)
transformer = tableau_entiers_aleatoires
print(transformer )

[ 1  8  2  6  4 10  8  2  9  5  9  4  8  6  7  8  1  4  2  3]


In [119]:
13#Transformer le tableau précédent en matrice de 4 lignes et 5 colonnes
T = transformer.reshape(4, 5)
print(T)

[[ 1  8  2  6  4]
 [10  8  2  9  5]
 [ 9  4  8  6  7]
 [ 8  1  4  2  3]]


In [48]:
14#Créer un tableau de 5 éléments compris entre 0 et 1 avec une amplitude égale
tableau_amplitude_egale = np.linspace(0, 1, 5)
print(tableau_amplitude_egale)

[0.   0.25 0.5  0.75 1.  ]


In [59]:
#Chercher a comprendre
tableau_amplitude_egale =  np.arange(0, 1.2, 0.25)
print(tableau_amplitude_egale)

[0.   0.25 0.5  0.75 1.  ]


Exercice 2 : les attributs d'un tableau numpy

In [62]:
#1. Afficher le nombre de lignes et de colonnes
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [71]:
#2. Afficher la dimension de mon tableau
dimension = a.ndim
print(dimension)

2


In [70]:
#3. Afficher le nombre d'élément de mon tableau
nombre_elements = a.size
print(nombre_elements)

9


In [72]:
#4. Afficher le type des éléments du tableau
type_elements = a.dtype
print(type_elements)

int64


Exercice 3 : Indexing, slicing, subsetting, masking

In [73]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [82]:
#1. afficher la valeur 5 qui est dans le tableau
print(a[1, 1])

5


In [86]:
#2. Remplacer le 5 qui est dans le tableau par 0
a[1, 1] = 0
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [91]:
#3. afficher les chiffres 3, 6 et 9 du tableau
print(a[0:3, 2])

[3 6 9]


In [96]:
#4. créer un tableau de 4 lignes et 3 colonnes rempli de 12 nombres entiers aléatoires compris entre 0 et 9
tableau_entiers_aleatoires = np.random.randint(0, 10, 12)
tableau = tableau_entiers_aleatoires.reshape(4, 3)
print(tableau)

[[5 1 9]
 [8 7 7]
 [1 7 0]
 [5 1 1]]


In [131]:
#4. créer un tableau de 4 lignes et 3 colonnes rempli de 12 nombres entiers aléatoires compris entre 0 et 9
tableau3 = np.random.randint(0, 10, size=(4, 3))
b=tableau3
print(tableau3)

[[5 3 7]
 [5 4 0]
 [9 2 8]
 [7 6 4]]


In [133]:
#5.Vérifier qu’il y a des nombres inférieur à 5
resultat = np.any(b<5)
print(resultat)

True


In [134]:
#6. Remplacer les nombres inférieurs à 5 par 0
b[b < 5] = 0
print(b)

[[5 0 7]
 [5 0 0]
 [9 0 8]
 [7 6 0]]


Exercice 4 :

In [142]:
#1. Créer un tableau de 4 lignes et 3 colonnes rempli de 11 nombres entiers aléatoires compris entre 0 et 9
tableau3 = np.random.randint(0, 10, size=(4, 3))
print(tableau3)

[[5 1 2]
 [8 1 3]
 [8 4 2]
 [3 1 6]]


In [144]:
#2. Quel est le type des éléments du tableau ?
type_des_éléments=tableau3.dtype
print(type_des_éléments)

int64


In [145]:
#3. Changer de type des éléments du tableau en float32
tableau = tableau3.astype(np.float32)
print(tableau)

[[5. 1. 2.]
 [8. 1. 3.]
 [8. 4. 2.]
 [3. 1. 6.]]


In [146]:
#4. Ajouter le chiffre 3 à la fin du tableau à une dimension
tableau8= np.append(tableau, 3)
print(tableau8)

[5. 1. 2. 8. 1. 3. 8. 4. 2. 3. 1. 6. 3.]


In [150]:
#5. Transformer le tableau en matrice dénommée “a” de 3 lignes et 4 colonnes
a = np.delete(tableau8, -1)
a= a.reshape(3, 4)
print(a)

[[5. 1. 2. 8.]
 [1. 3. 8. 4.]
 [2. 3. 1. 6.]]


In [156]:
#6. Créer une matrice dénommée “b” de 3 lignes et 4 colonnes remplie de série d'entiers successifs allant de 1 à 12 inclus
b = np.random.randint(1, 13, size=(3, 4))
print(b)

[[ 3  5 12 10]
 [ 1  5  8 11]
 [ 6  2  8 11]]


In [157]:
#7. Créer une matrice dénommée “c” qui est la concaténation des deux tableaux “a” et “b” dans le sens horizontale
c = np.hstack((a, b))
print(c)

[[ 5.  1.  2.  8.  3.  5. 12. 10.]
 [ 1.  3.  8.  4.  1.  5.  8. 11.]
 [ 2.  3.  1.  6.  6.  2.  8. 11.]]


In [159]:
#8. Créer une matrice dénommée “d” qui est la concaténation des deux tableaux “a” et “b” dans le sens vertical
d= np.vstack((a, b))
print(c)

[[ 5.  1.  2.  8.]
 [ 1.  3.  8.  4.]
 [ 2.  3.  1.  6.]
 [ 3.  5. 12. 10.]
 [ 1.  5.  8. 11.]
 [ 6.  2.  8. 11.]]


In [160]:
#9. Aplatir un tableau “d”
aplat = d.ravel()
print(aplat)

[ 5.  1.  2.  8.  1.  3.  8.  4.  2.  3.  1.  6.  3.  5. 12. 10.  1.  5.
  8. 11.  6.  2.  8. 11.]


In [161]:
#10.Supprimer dernier élément du tableau
e = np.delete(aplat, 23)
print(e)

[ 5.  1.  2.  8.  1.  3.  8.  4.  2.  3.  1.  6.  3.  5. 12. 10.  1.  5.
  8. 11.  6.  2.  8.]


Exercice : Statistique avec numpy

In [162]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [165]:
#1. Afficher la somme des éléments du tableau
somme = np.sum(a)
print(somme)

45


In [166]:
#2. Afficher la somme des éléments du tableau par colonne
somme_par_colonne = np.sum(a, axis=0)
print(somme_par_colonne)

[12 15 18]


In [167]:
#3. Afficher la somme des éléments du tableau par ligne
somme_par_ligne = np.sum(a, axis=1)
print(somme_par_ligne)

[ 6 15 24]


In [168]:
#4. Afficher le produit des éléments du tableau par colonne
prod_par_ligne = np.prod(a, axis=0)
print(prod_par_ligne)

[ 28  80 162]


In [169]:
#5. Afficher le minimum du tableau
minimum = np.min(a)
print(minimum)

1


In [170]:
#6. Afficher le maximum des éléments du tableau
maximun = np.max(a)
print(maximun)

9


In [172]:
#7. Afficher la moyenne des éléments du tableau
moyenne = np.mean(a)
print(moyenne)

5.0


In [173]:
#8. Afficher la variance des éléments du tableau
variance = np.var(a)
print(variance)

6.666666666666667


In [174]:
#9. Afficher l’écart type des éléments du tableau
ecart_type = np.std(a)
print(ecart_type)

2.581988897471611
